server:
  port: 8080

spring:
  ai:
    openai:
      api-key: sk-82fe2fcd6d4547cda27825b16d6765ef
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat # v3
#          model: deepseek-reasoner # R1
    chat:
      client:
        advisor: DEBUG