server:
  port: 8080

spring:
  ai:
    openai:
      api-key: sk-82fe2fcd6d4547cda27825b16d6765ef111
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat # v3
#          model: deepseek-reasoner # R1
    chat:
      client:
        advisor: DEBUG

    vectorstore:
      milvus:
        client:
          host: "192.168.217.130"
          port: 19530